program AliGHAFFARIYAN
implicit none
integer i,j,k,ii,jj,kk,n,state
integer face(3,1510),facenode1(3,1510),facenode2(3,1510),node(3,1510)
integer InfNB(50),Wall11NB(10),Wall13NB(9),Wall21NB(13),Wall23NB(6),nb(3,1510)
double precision u(4,1510),w(4,1510)
double precision Linf,L(4,1510)
double precision roinf,Minf,gama,Pinf,Einf,usinf,AOA,pi
double precision ein,a1,a2,Tinf,cv,cp,Rc,Tstart,Tend
double precision deltaXface(3,1510),deltaYface(3,1510),deltaS(3,1510),xcell(1510),ycell(1510)
double precision tet(1510),prel(1510),Tr(1510),arctan(1510), x(755),y(755)
double precision Area(1510),R11(3,1510),R12(3,1510),R13(3,1510),R14(3,1510)
double precision R21(3,1510),R22(3,1510),R23(3,1510),R24(3,1510),R31(3,1510),R32(3,1510),R33(3,1510)
double precision R34(3,1510),R41(3,1510),R42(3,1510),R43(3,1510),R44(3,1510),q(3,1510),r(3,1510)
double precision ut(1510),ur(1510),c(1510),ro(1510),p(1510),T(1510),roHat(3,1510),uHat(3,1510)
double precision vHat(3,1510),cHat(3,1510),HHat(3,1510),rHat(3,1510),qHat(3,1510),Phi1(3,1510)
double precision Phi2(3,1510),Phi3(3,1510),Phi4(3,1510),a(4,1510),deltaP(3,1510)
double precision deltaRO(3,1510),deltaQ(3,1510),deltaR(3,1510),deltaV1(3,1510),deltaV2(3,1510)
double precision deltaV3(3,1510),deltaV4(3,1510),sigma1(3,1510),sigma2(3,1510),sigma3(3,1510)
double precision sigma4(3,1510),PhiTot1(3,1510),PhiTot2(3,1510),PhiTot3(3,1510),PhiTot4(3,1510)
double precision SigmaPhiTot(4,1510),deltatime(1510),Res(4,1510),sigmadeltaXcell(1510)
double precision sigmadeltaYcell(1510),M(1510),Mnode(755),m1(755),m2(755),alpha(6)
double precision Ent(1510),Ent1(755),Fx,Fy,Cd,Cl,Lift,Drag,u1(755),v1(755),c1(755),p1(755)
double precision ro1(755),Unode(755),Vnode(755),Cnode(755),CPnode(755),ENTnode(755),Pnode(755)
double precision ROnode(755)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
pi=4*atan(1.0)
roinf=1.0
usinf=1.0
!uinf=1202.0
!Tinf=56.86
Rc=287.0
gama=1.4
cv=Rc/(gama-1.0)   
cp=Rc*gama/(gama-1.0)

!Determining the infinity Mach number:
write(*,*) 'If the flow is uniform please enter 1 and if it is inviscid please enter 2 '
read(*,*) STATE

!Determining the infinity Mach number:
! write (*,*) 'Please enter the infinity Mach number '
!  read (*,*) Minf 
!Determining the angle of attack:
! write (*,*) 'Please enter the angle of attack '
!  read (*,*) AOA 

Minf=0.8
AOA =0.0*pi/180.0 

!Tinf/(uinf**2.0)=1/(gama*Rc*Minf**2.0)
!Einf=cv*Tinf/(uinf**2.0) +usinf**2.0/2.0
!Pinf=roinf*Rc*Tinf/(uinf**2.0)
Tinf=1.0/(gama*Rc*Minf**2.0)
Einf=cv/(gama*Rc*Minf**2.0) +usinf**2.0/2.0
Pinf=roinf*Tinf*Rc

!nodei(j) is the i'th node of the j'th cell which is generated by Najat program.
!Najat totally produces 755 nodes and 1422 cells. 
do j=1,1422
open(1,file='1.txt')
read(1,*)  node(1,j)	

open(2,file='2.txt')
read(2,*)  node(2,j)

open(3,file='3.txt')
read(3,*)  node(3,j)
enddo

!x(i) & y(i) are the coordinates of the i'th cell:
do i=1,755
open(6,file='X of nodes.txt')
read(6,*)  x(i)

open(7,file='Y of nodes.txt')
read(7,*)  y(i)
enddo

!a1=y(76)-y(75)
!a1=a1+y(75)-y(161)
!a1=a1+y(161)-y(76)
!write(*,*) a1

!Area(j) is the area of the j'th cell:
do j=1,1422
Area(j)=0.5*abs( ( x(node(2,j))-x(node(1,j)) )*( y(node(3,j))-y(node(1,j)) )+( y(node(2,j))-y(node(1,j)) )*( x(node(3,j))-x(node(1,j)) ) )
!open(8,file='Area of cells.txt')
!write(8,*)  Area(j)
enddo

do j=1,1422
xcell(j)=( x(node(1,j))+x(node(2,j))+x(node(3,j)) )/3.0
ycell(j)=( y(node(1,j))+y(node(2,j))+y(node(3,j)) )/3.0
!tet(j)=atan(ycell(j)/xcell(j))
enddo

do j=1,1510
u(1,j)=roinf
u(2,j)=roinf*usinf*cos(AOA)
u(3,j)=roinf*usinf*sin(AOA) 
u(4,j)=roinf*Einf 
enddo

do j=1,1510
 ro(j)=u(1,j)
 ut(j)=u(2,j)/ro(j)
 ur(j)=u(3,j)/ro(j)
 T(j)=Tinf
 p(j)=Pinf
enddo

CALL NeighBourhood(i,j,node,nb)            !Line:199
CALL FaceEndPoints(i,j,k,node,face,facenode1,facenode2) !Line:465
CALL BoundaryNeighBourhoodandFaces(i,j,kk,nb,InfNB,Wall11NB,Wall13NB,Wall21NB,Wall23NB)!Line:622

!write(*,*) facenode1(1,3),facenode2(1,3),facenode1(2,3),facenode2(2,3),facenode1(3,3),facenode2(3,3)  


open(4,file='nb.txt')
do j=1,1510
write(4,*) 'Neighbours of',j,'    are:',nb(1,j),nb(2,j),nb(3,j)
enddo

open(5,file='faceEndpoints.txt')
open(17,file='face.txt')
do j=1,1422
do i=1,3
write(5,*) 'Endpoints of face(',i,',',j,')=',facenode1(i,j),facenode2(i,j)
write(17,*) 'face',i,',',j,'=',face(i,j)
enddo
enddo


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
do j=1,1422
do i=1,3
deltaXface(i,j)= x(facenode1(i,j))-x(facenode2(i,j))
deltaYface(i,j)= y(facenode1(i,j))-y(facenode2(i,j))
deltaS(i,j)=sqrt( (deltaXface(i,j))**2.0 +(deltaYface(i,j))**2.0 )
enddo
enddo

!do j=1,1422
!sigmadeltaXcell(j)= deltaXface(1,j)+deltaXface(2,j)+deltaXface(3,j)
!sigmadeltaYcell(j)= deltaYface(1,j)+deltaYface(2,j)+deltaYface(3,j)
!enddo

!deltaYface(1,3)= y(facenode1(1,3))-y(facenode2(1,3))
!deltaYface(2,3)= y(facenode1(2,3))-y(facenode2(2,3))
!deltaYface(3,3)= y(facenode1(3,3))-y(facenode2(3,3))

!write(*,*) deltaYface(1,3),deltaYface(2,3),deltaYface(3,3)
!a1=deltaYface(1,3)+deltaYface(2,3)+deltaYface(3,3)
!write(*,*) a1

!@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ 
DO n=1,10000000
  
 do j=1,1422
   if (T(j)<0.0) then
   write(*,*) j	
   a2=10.0
   endif
   enddo

  if(a2==10.0) then
 exit 
 endif

  Linf=0.0

  do j=1,1510
  !c(j)=sqrt(gama*Rc*T(j))/uinf
   c(j)=sqrt(gama*Rc*T(j))
  enddo

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
do j=1,1422
do i=1,3
q(i,j)=( ut(j)*deltaYface(i,j)-ur(j)*deltaXface(i,j) )/deltaS(i,j)
r(i,j)=( ut(j)*deltaXface(i,j)+ur(j)*deltaYface(i,j) )/deltaS(i,j)

Phi1(i,j)=ro(j)*q(i,j)
Phi2(i,j)=ro(j)*q(i,j)*ut(j) +p(j)*deltaYface(i,j)/deltaS(i,j)
Phi3(i,j)=ro(j)*q(i,j)*ur(j) -p(j)*deltaXface(i,j)/deltaS(i,j)
!Phi4(i,j)=ro(j)*q(i,j)*( cp*T(j)/uinf**2.0 +0.5*(ur(j)**2.0+ut(j)**2.0) )
Phi4(i,j)=ro(j)*q(i,j)*( cp*T(j)+0.5*(ur(j)**2.0+ut(j)**2.0) )

do kk=1,3
if (nb(kk,nb(i,j))==j) then

!Inviscid Flow:
IF (STATE==2)THEN
if (nb(i,j)>1472) then

q(kk,nb(i,j))=-q(i,j)
r(kk,nb(i,j))=r(i,j)

ut(nb(i,j))=(-q(i,j)*(deltaYface(i,j))+r(i,j)*(deltaXface(i,j)))/deltaS(i,j)
ur(nb(i,j))=(q(i,j)*(deltaXface(i,j))+r(i,j)*(deltaYface(i,j)))/deltaS(i,j)

else if(nb(i,j)<=1472) then 
q(kk,nb(i,j))=(ut(nb(i,j))*deltaYface(i,j)-ur(nb(i,j))*deltaXface(i,j))/deltaS(i,j)
r(kk,nb(i,j))=(ut(nb(i,j))*deltaXface(i,j)+ur(nb(i,j))*deltaYface(i,j))/deltaS(i,j)
endif
ENDIF

IF(STATE==1)THEN
q(kk,nb(i,j))=(ut(nb(i,j))*deltaYface(i,j)-ur(nb(i,j))*deltaXface(i,j))/deltaS(i,j)
r(kk,nb(i,j))=(ut(nb(i,j))*deltaXface(i,j)+ur(nb(i,j))*deltaYface(i,j))/deltaS(i,j)
ENDIF

Phi1(i,j)=ro(nb(i,j))*q(kk,nb(i,j))+Phi1(i,j)
Phi2(i,j)=ro(nb(i,j))*q(kk,nb(i,j))*ut(nb(i,j)) +p(nb(i,j))*deltaYface(i,j)/deltaS(i,j)+Phi2(i,j)
Phi3(i,j)=ro(nb(i,j))*q(kk,nb(i,j))*ur(nb(i,j)) -p(nb(i,j))*deltaXface(i,j)/deltaS(i,j)+Phi3(i,j)
!Phi4(i,j)=ro(nb(i,j))*q(kk,nb(i,j))*( cp*T(nb(i,j))/uinf**2.0 +0.5*(ur(nb(i,j))**2.0+ut(nb(i,j))**2.0) )+Phi4(i,j)
Phi4(i,j)=ro(nb(i,j))*q(kk,nb(i,j))*( cp*T(nb(i,j))+0.5*(ur(nb(i,j))**2.0+ut(nb(i,j))**2.0) )+Phi4(i,j)

deltaQ(i,j)=q(kk,nb(i,j))-q(i,j)
deltaR(i,j)=r(kk,nb(i,j))-r(i,j)

endif
enddo

roHat(i,j)=(ro(j)*ro(nb(i,j)))**0.5
uHat(i,j)=( (ro(j)**0.5)*ut(j) +(ro(nb(i,j))**0.5)*ut(nb(i,j)) )/( ro(j)**0.5 +ro(nb(i,j))**0.5 )
vHat(i,j)=( (ro(j)**0.5)*ur(j) +(ro(nb(i,j))**0.5)*ur(nb(i,j)) )/( ro(j)**0.5 +ro(nb(i,j))**0.5 )

qHat(i,j)=(uHat(i,j)*deltaYface(i,j)-vHat(i,j)*deltaXface(i,j))/deltaS(i,j)
rHat(i,j)=(uHat(i,j)*deltaXface(i,j)+vHat(i,j)*deltaYface(i,j))/deltaS(i,j)

!HHat(i,j)=( (ro(j)**0.5)*( cp*T(j)/uinf**2.0 +0.5*(ur(j)**2.0+ut(j)**2.0) ) +(ro(nb(i,j))**0.5)*( cp*T(nb(i,j))/uinf**2.0 +0.5*(ur(nb(i,j))**2.0+ut(nb(i,j))**2.0) ) )/( ro(j)**0.5 +ro(nb(i,j))**0.5 )
HHat(i,j)=( (ro(j)**0.5)*( cp*T(j)+0.5*(ur(j)**2.0+ut(j)**2.0) ) +(ro(nb(i,j))**0.5)*( cp*T(nb(i,j))+0.5*(ur(nb(i,j))**2.0+ut(nb(i,j))**2.0) ) )/( ro(j)**0.5 +ro(nb(i,j))**0.5 )
!cHat(i,j)=( (ro(j)**0.5)*c(j) +(ro(nb(i,j))**0.5)*c(nb(i,j)) )/( ro(j)**0.5 +ro(nb(i,j))**0.5 )!
cHat(i,j)=sqrt( (gama-1.0)*( HHat(i,j)-0.5*(uHat(i,j)**2.0+vHat(i,j)**2.0) ) )

!a(i,j) is the i'th array of jth cell's [a] matrix:
a(1,j)=qHat(i,j)-cHat(i,j)
a(2,j)=qHat(i,j)
a(3,j)=qHat(i,j)
a(4,j)=qHat(i,j)+cHat(i,j)

deltaP(i,j)=p(nb(i,j))-p(j)
deltaRO(i,j)=ro(nb(i,j))-ro(j)

deltaV1(i,j)=( deltaP(i,j)-roHat(i,j)*cHat(i,j)*deltaQ(i,j) ) / (2.0*cHat(i,j)**2.0)
deltaV2(i,j)=roHat(i,j)*deltaR(i,j)/cHat(i,j)
deltaV3(i,j)=deltaRO(i,j)-deltaP(i,j)/(cHat(i,j)**2.0)
deltaV4(i,j)=( deltaP(i,j)+roHat(i,j)*cHat(i,j)*deltaQ(i,j) ) / (2.0*cHat(i,j)**2.0)

!Rij is the ij array of [R^] matrix:
R11(i,j)=1.0
R12(i,j)=0.0
R13(i,j)=1.0
R14(i,j)=1.0

R21(i,j)=uHat(i,j)-cHat(i,j)*deltaYface(i,j)/deltaS(i,j)
R22(i,j)=cHat(i,j)*deltaXface(i,j)/deltaS(i,j)
R23(i,j)=uHat(i,j)
R24(i,j)=uHat(i,j)+cHat(i,j)*deltaYface(i,j)/deltaS(i,j)

R31(i,j)=vHat(i,j)+cHat(i,j)*deltaXface(i,j)/deltaS(i,j)
R32(i,j)=cHat(i,j)*deltaYface(i,j)/deltaS(i,j)
R33(i,j)=vHat(i,j)
R34(i,j)=vHat(i,j)-cHat(i,j)*deltaXface(i,j)/deltaS(i,j)

R41(i,j)=HHat(i,j)-qHat(i,j)*cHat(i,j)
R42(i,j)=rHat(i,j)*cHat(i,j)
R43(i,j)=0.5*(uHat(i,j)**2.0+vHat(i,j)**2.0)
R44(i,j)=HHat(i,j)+qHat(i,j)*cHat(i,j)

sigma1(i,j)=abs(a(1,j))*deltaV1(i,j) +abs(a(3,j))*deltaV3(i,j) +abs(a(4,j))*deltaV4(i,j)

sigma2(i,j)=abs(a(1,j))*deltaV1(i,j)*R21(i,j) +abs(a(2,j))*deltaV2(i,j)*R22(i,j) +abs(a(3,j))*deltaV3(i,j)*R23(i,j) +abs(a(4,j))*deltaV4(i,j)*R24(i,j)

sigma3(i,j)=abs(a(1,j))*deltaV1(i,j)*R31(i,j) +abs(a(2,j))*deltaV2(i,j)*R32(i,j) +abs(a(3,j))*deltaV3(i,j)*R33(i,j) +abs(a(4,j))*deltaV4(i,j)*R34(i,j)

sigma4(i,j)=abs(a(1,j))*deltaV1(i,j)*R41(i,j) +abs(a(2,j))*deltaV2(i,j)*R42(i,j) +abs(a(3,j))*deltaV3(i,j)*R43(i,j) +abs(a(4,j))*deltaV4(i,j)*R44(i,j)
enddo
enddo

!PhiTotk(i,j) is the k'th array of [U] matrix Phi(Ul,Ur) which belongs to i'th face of j'th cell:
  do j=1,1422
  do i=1,3 
  PhiTot1(i,j)=0.5*Phi1(i,j) -0.5*sigma1(i,j)
  PhiTot2(i,j)=0.5*Phi2(i,j) -0.5*sigma2(i,j)
  PhiTot3(i,j)=0.5*Phi3(i,j) -0.5*sigma3(i,j)
  PhiTot4(i,j)=0.5*Phi4(i,j) -0.5*sigma4(i,j)
  enddo
  enddo

!SigmaPhiTot(ii,j) is the sum of PhiTotii(i,j) for all faces of a cell:
  do j=1,1422
  SigmaPhiTot(1,j)=PhiTot1(1,j)*deltaS(1,j)+PhiTot1(2,j)*deltaS(2,j)+PhiTot1(3,j)*deltaS(3,j)
  SigmaPhiTot(2,j)=PhiTot2(1,j)*deltaS(1,j)+PhiTot2(2,j)*deltaS(2,j)+PhiTot2(3,j)*deltaS(3,j)
  SigmaPhiTot(3,j)=PhiTot3(1,j)*deltaS(1,j)+PhiTot3(2,j)*deltaS(2,j)+PhiTot3(3,j)*deltaS(3,j)
  SigmaPhiTot(4,j)=PhiTot4(1,j)*deltaS(1,j)+PhiTot4(2,j)*deltaS(2,j)+PhiTot4(3,j)*deltaS(3,j)
  !do i=1,4
  !if (SigmaPhiTot(i,j)<10.d-14) then
  !SigmaPhiTot(i,j)=0.0
  !endif
  !enddo
  enddo


  do j=1,1422
  a2=( ABS(qHat(1,j))+cHat(1,j) )*deltaS(1,j)+( ABS(qHat(2,j))+cHat(2,j) )*deltaS(2,j)+(ABS(qHat(3,j))+cHat(3,j))*deltaS(3,j)	
    
  deltatime(j)=1.0*Area(j)/a2
  enddo 

!Residual calculation and data update:
   
   !go to 6
   alpha(1)=0.0485
   alpha(2)=0.1120
   alpha(3)=0.1994
   alpha(4)=0.3285
   alpha(5)=0.5477
   alpha(6)=1.0
   !6 continue


   do j=1,1422
   do ii=1,4
   Res(ii,j)=-SigmaPhiTot(ii,j)/Area(j)
   do k=1,6
   w(ii,j) = u(ii,j)+deltatime(j)*Res(ii,j)*alpha(k)
   u(ii,j)=w(ii,j)
   enddo  
   L(ii,j) = abs(Res(ii,j))
   if (L(ii,j)>Linf) then 
   Linf = L(ii,j)
   end if 
   enddo
   enddo

  do kk=1,1422
  
  ro(kk)=u(1,kk)
  ut(kk)=u(2,kk)/ro(kk)
  ur(kk)=u(3,kk)/ro(kk)
  !T(kk)=( u(4,kk)/ro(kk)-0.5*( ut(kk)**2.0+ur(kk)**2.0 ) )*(gama-1.0)*(uinf**2.0)/Rc
  T(kk)=( u(4,kk)/ro(kk)-0.5*( ut(kk)**2.0+ur(kk)**2.0 ) )/cv
  !p(kk)=ro(kk)*Rc*T(kk)/(uinf**2.0)  
  p(kk)=ro(kk)*Rc*T(kk)
  
  enddo 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  
!Inviscid Flow(Wall Boundary):

  do kk=1473,1482
  ro(kk)=ro(nb(1,kk))
  T(kk)=T(nb(1,kk))
  p(kk)=p(nb(1,kk))
  enddo 

  do kk=1483,1491
  ro(kk)=ro(nb(3,kk))
  T(kk)=T(nb(3,kk))
  p(kk)=p(nb(3,kk))
  enddo 
  
  do kk=1492,1504
  ro(kk)=ro(nb(1,kk))
  T(kk)=T(nb(1,kk))
  p(kk)=p(nb(1,kk))
  enddo 
  
  do kk=1505,1510
  ro(kk)=ro(nb(3,kk))
  T(kk)=T(nb(3,kk))
  p(kk)=p(nb(3,kk))
  enddo 
 
!!!!!!!!!!!!!!!!!!!!
  do j=1,1510
   if (ro(j)<0.0) then
   write(*,*) j
   a2=10.0
   endif
  enddo

  if(a2==10.0) then
  exit 
  endif

write(*,*) Linf

do k=1,10000
if (n==100*k) then
a1=n
write(*,*) a1,a1,a1,a1,a1,a1,a1,a1,a1,a1,a1,a1,a1,a1,a1,a1,a1,a1,a1
write(*,*) a1,a1,a1,a1,a1,a1,a1,a1,a1,a1,a1,a1,a1,a1,a1,a1,a1,a1,a1
endif
enddo
 
  if (n>1000) then
  if (Linf<10.d-3) then
	
	open(1,file='Contours.plt')
	
    do i=1,755	
	do j=1,1422		
	do k=1,3
	if (i==node(k,j)) then
	
	u1(i)=ut(j)*Area(j)+u1(i)
	v1(i)=ur(j)*Area(j)+v1(i)
	c1(i)=c(j)*Area(j)+c1(i)
	p1(i)=p(j)*Area(j)+p1(i)
	ro1(i)=ro(j)*Area(j)+ro1(i)
	m2(i)=Area(j)+m2(i)	

	endif
	enddo    	
	enddo
	
	Unode(i)=u1(i)/m2(i)
    Vnode(i)=v1(i)/m2(i)
	Cnode(i)=c1(i)/m2(i)
	Mnode(i)=sqrt( (Unode(i)**2.0+Vnode(i)**2.0) )/Cnode(i) 
	
	Pnode(i)=p1(i)/m2(i)
	CPnode(i)=2.0*(Pnode(i)-Pinf)/(roinf*usinf**2.0)
	
	ROnode(i)=ro1(i)/m2(i)
	ENTnode(i)=(Pnode(i)/Pinf)/( (ROnode(i)/roinf)**gama ) -1.0
	enddo

    do i=1,755
	open(19,file='M.txt')
	write(19,*)  Mnode(i)   
	enddo	

    Fx=0.0
	Fy=0.0
	do j=1,10
	Fx=-p(Wall11NB(j))*deltaYface(1,Wall11NB(j))+Fx
    Fy=p(Wall11NB(j))*deltaXface(1,Wall11NB(j))+Fy
	enddo
    
	do j=1,9
	Fx=-p(Wall13NB(j))*deltaYface(3,Wall13NB(j))+Fx
    Fy=p(Wall13NB(j))*deltaXface(3,Wall13NB(j))+Fy
	enddo
	
	do j=1,13
	Fx=-p(Wall21NB(j))*deltaYface(1,Wall21NB(j))+Fx
    Fy=p(Wall21NB(j))*deltaXface(1,Wall21NB(j))+Fy
	enddo
	
	do j=1,6
	Fx=-p(Wall23NB(j))*deltaYface(3,Wall23NB(j))+Fx
    Fy=p(Wall23NB(j))*deltaXface(3,Wall23NB(j))+Fy
	enddo
    
	Lift=cos(AOA)*Fy-sin(AOA)*Fx
	Drag=sin(AOA)*Fy+cos(AOA)*Fx

	Cl=2.0*Lift/(roinf*usinf**2.0)
    Cd=2.0*Drag/(roinf*usinf**2.0)
    write(*,*) 'Cl=',-Cl,'Cd=',-Cd
	
	
	write(1,*) 'Variables=x,y,M,Cp,Entrophy'
	write(1,*) 'ZONE F=FEPOINT,ET=TRIANGLE,N= 755 ,E= 1422'
    do i=1,755
	write(1,*)  x(i),y(i),Mnode(i),CPnode(i),ENTnode(i)
	enddo
	do j=1,1422	
    write(1,*)  node(1,j),node(2,j),node(3,j)
	enddo

	open(22,file='M.plt')
	write(22,*)  xcell(Wall21NB(1)),M(Wall21NB(1))
	write(22,*)  xcell(Wall23NB(1)),M(Wall23NB(1))
	do j=2,11
	write(22,*)  xcell(Wall21NB(j)),M(Wall21NB(j))
	enddo
	do j=2,6
    write(22,*)  xcell(Wall23NB(j)),M(Wall23NB(j))
	enddo
    do j=12,13
	write(22,*)  xcell(Wall21NB(j)),M(Wall21NB(j))
	enddo
	
	exit
  endif
  endif

 
ENDDO

write(*,*) n

!############################################################################################
!############################################################################################

CONTAINS

double precision function ff(z)
implicit none
double precision z
ff=atan(z)
end function ff 

double precision function gg(z)
implicit none
double precision z
gg=sin(z)
end function gg
 
double precision function hh(z)
implicit none
double precision z
hh=cos(z)
end function hh 

!***************************************************
SUBROUTINE NeighBourhood(i,j,node,nb)
integer i,j,k,node(3,1510),nb(3,1510)

!nb(i,j) is the i'th neighbour of the j'th cell which is generated by Najat program:
do j=1,1422
do i=1,1422

if (node(1,j)==node(2,i)) then
if (node(2,j)==node(3,i)) then
nb(1,j)=i
endif
endif

if (node(1,j)==node(2,i)) then
if (node(2,j)==node(1,i)) then
nb(1,j)=i
endif
endif

if (node(1,j)==node(3,i)) then
if (node(2,j)==node(1,i)) then 
nb(1,j)=i
endif
endif

if (node(1,j)==node(1,i)) then
if (node(2,j)==node(3,i)) then 
nb(1,j)=i
endif
endif

if (node(1,j)==node(3,i)) then
if (node(2,j)==node(2,i)) then 
nb(1,j)=i
endif
endif

!@@@!!!!!!!!!!!!!!!!!!!!!!
if (node(1,j)==node(2,i)) then
if (node(3,j)==node(1,i)) then 
nb(3,j)=i
endif
endif

if (node(1,j)==node(3,i)) then
if (node(3,j)==node(2,i)) then 
nb(3,j)=i
endif
endif

if (node(1,j)==node(3,i)) then
if (node(3,j)==node(1,i)) then 
nb(3,j)=i
endif
endif

if (node(1,j)==node(1,i)) then
if (node(3,j)==node(2,i)) then 
nb(3,j)=i
endif
endif

if (node(1,j)==node(2,i)) then
if (node(3,j)==node(3,i)) then 
nb(3,j)=i
endif
endif

!@@@!!!!!!!!!!!!!!!!!!!!!!
if (node(2,j)==node(3,i)) then
if (node(3,j)==node(2,i)) then 
nb(2,j)=i
endif
endif

if (node(2,j)==node(3,i)) then
if (node(3,j)==node(1,i)) then 
nb(2,j)=i
endif
endif

if (node(2,j)==node(1,i)) then
if (node(3,j)==node(2,i)) then 
nb(2,j)=i
endif
endif

if (node(2,j)==node(1,i)) then
if (node(3,j)==node(3,i)) then 
nb(2,j)=i
endif
endif

if (node(2,j)==node(2,i)) then
if (node(3,j)==node(1,i)) then 
nb(2,j)=i
endif
endif

enddo
enddo

return
END SUBROUTINE

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
SUBROUTINE FaceEndPoints(i,j,k,node,face,facenode1,facenode2)!Line:110
integer i,j,k,node(3,1510)
integer face(3,1510),facenode1(3,1510),facenode2(3,1510)

!k,is the face number which is drawn between facenode1(k) & facenode2(k):
k=0
do j=1,1422
do i=1,j
 
if (node(1,j)==node(2,i)) then
if (node(2,j)==node(3,i)) then
k=k+1
face(1,j)=k
face(2,i)=k
facenode1(1,j)=node(1,j)
facenode2(1,j)=node(2,j)
facenode1(2,i)=node(2,i)
facenode2(2,i)=node(3,i)
endif
endif

if (node(1,j)==node(2,i)) then
if (node(2,j)==node(1,i)) then
k=k+1
face(1,j)=k
face(1,i)=k
facenode1(1,j)=node(1,j)
facenode2(1,j)=node(2,j)
facenode1(1,i)=node(1,i)
facenode2(1,i)=node(2,i)
endif
endif

if (node(1,j)==node(3,i)) then
if (node(2,j)==node(1,i)) then 
k=k+1
face(1,j)=k
face(3,i)=k
facenode1(1,j)=node(1,j)
facenode2(1,j)=node(2,j)
facenode1(3,i)=node(3,i)
facenode2(3,i)=node(1,i)
endif
endif

if (node(1,j)==node(1,i)) then
if (node(2,j)==node(3,i)) then 
k=k+1
face(1,j)=k
face(3,i)=k
facenode1(1,j)=node(1,j)
facenode2(1,j)=node(2,j)
facenode1(3,i)=node(3,i)
facenode2(3,i)=node(1,i)
endif
endif

if (node(1,j)==node(3,i)) then
if (node(2,j)==node(2,i)) then 
k=k+1
face(1,j)=k
face(2,i)=k
facenode1(1,j)=node(1,j)
facenode2(1,j)=node(2,j)
facenode1(2,i)=node(2,i)
facenode2(2,i)=node(3,i)
endif
endif

!***************************
if (node(1,j)==node(2,i)) then
if (node(3,j)==node(1,i)) then 
k=k+1
face(3,j)=k
face(1,i)=k
facenode1(3,j)=node(3,j)
facenode2(3,j)=node(1,j)
facenode1(1,i)=node(1,i)
facenode2(1,i)=node(2,i)
endif
endif

if (node(1,j)==node(3,i)) then
if (node(3,j)==node(2,i)) then 
k=k+1
face(3,j)=k
face(2,i)=k
facenode1(3,j)=node(3,j)
facenode2(3,j)=node(1,j)
facenode1(2,i)=node(2,i)
facenode2(2,i)=node(3,i)
endif
endif

if (node(1,j)==node(3,i)) then
if (node(3,j)==node(1,i)) then 
k=k+1
face(3,j)=k
face(3,i)=k
facenode1(3,j)=node(3,j)
facenode2(3,j)=node(1,j)
facenode1(3,i)=node(3,i)
facenode2(3,i)=node(1,i)

endif
endif

if (node(1,j)==node(1,i)) then
if (node(3,j)==node(2,i)) then 
k=k+1
face(3,j)=k
face(1,i)=k
facenode1(3,j)=node(3,j)
facenode2(3,j)=node(1,j)
facenode1(1,i)=node(1,i)
facenode2(1,i)=node(2,i)

endif
endif

if (node(1,j)==node(2,i)) then
if (node(3,j)==node(3,i)) then 
k=k+1
face(3,j)=k
face(2,i)=k
facenode1(3,j)=node(3,j)
facenode2(3,j)=node(1,j)
facenode1(2,i)=node(2,i)
facenode2(2,i)=node(3,i)
endif
endif

!***************************
if (node(2,j)==node(3,i)) then
if (node(3,j)==node(2,i)) then 
k=k+1
face(2,j)=k
face(2,i)=k
facenode1(2,j)=node(2,j)
facenode2(2,j)=node(3,j)
facenode1(2,i)=node(2,i)
facenode2(2,i)=node(3,i)
endif
endif

if (node(2,j)==node(3,i)) then
if (node(3,j)==node(1,i)) then 

k=k+1
face(2,j)=k
face(3,i)=k
facenode1(2,j)=node(2,j)
facenode2(2,j)=node(3,j)
facenode1(3,i)=node(3,i)
facenode2(3,i)=node(1,i)
endif
endif

if (node(2,j)==node(1,i)) then
if (node(3,j)==node(2,i)) then 
k=k+1
face(2,j)=k
face(1,i)=k
facenode1(2,j)=node(2,j)
facenode2(2,j)=node(3,j)
facenode1(1,i)=node(1,i)
facenode2(1,i)=node(2,i)
endif
endif

if (node(2,j)==node(1,i)) then
if (node(3,j)==node(3,i)) then 
k=k+1
face(2,j)=k
face(3,i)=k
facenode1(2,j)=node(2,j)
facenode2(2,j)=node(3,j)
facenode1(3,i)=node(3,i)
facenode2(3,i)=node(1,i)
endif
endif

if (node(2,j)==node(2,i)) then
if (node(3,j)==node(1,i)) then 
k=k+1
face(2,j)=k
face(1,i)=k
facenode1(2,j)=node(2,j)
facenode2(2,j)=node(3,j)
facenode1(1,i)=node(1,i)
facenode2(1,i)=node(2,i)
endif
endif

enddo
enddo

return
END SUBROUTINE

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
SUBROUTINE BoundaryNeighBourhoodandFaces(i,j,kk,nb,InfNB,Wall11NB,Wall13NB,Wall21NB,Wall23NB)!Line:58
integer i,j,kk,nb(3,1510),InfNB(50),Wall11NB(10),Wall13NB(9),Wall21NB(13),Wall23NB(6)

!k is continued from last subroutine:
k=k-1
kk=1423
do j=1,50
open(8,file='Inf NBs.txt')
read(8,*)  InfNB(j)
nb(3,InfNB(j))=kk
nb(3,kk)=InfNB(j)
k=k+1
face(3,InfNB(j))=k
face(3,kk)=k
facenode1(3,InfNB(j))=node(3,InfNB(j))
facenode2(3,InfNB(j))=node(1,InfNB(j))
kk=kk+1
enddo

kk=1473
do j=1,10
open(9,file='Wall11 NBs.txt')
read(9,*)  Wall11NB(j)
nb(1,Wall11NB(j))=kk
nb(1,kk)=Wall11NB(j)
Area(kk)=Area(Wall11NB(j))
k=k+1
face(1,Wall11NB(j))=k
face(1,kk)=k
facenode1(1,Wall11NB(j))=node(1,Wall11NB(j))
facenode2(1,Wall11NB(j))=node(2,Wall11NB(j))
kk=kk+1
enddo

kk=1483
do j=1,9
open(10,file='Wall13 NBs.txt')
read(10,*)  Wall13NB(j)
nb(3,Wall13NB(j))=kk
nb(3,kk)=Wall13NB(j)
Area(kk)=Area(Wall13NB(j))
k=k+1
face(3,Wall13NB(j))=k
face(3,kk)=k
facenode1(3,Wall13NB(j))=node(3,Wall13NB(j))
facenode2(3,Wall13NB(j))=node(1,Wall13NB(j))
kk=kk+1
enddo

kk=1492
do j=1,13
open(11,file='Wall21 NBs.txt')
read(11,*)  Wall21NB(j)
nb(1,Wall21NB(j))=kk
nb(1,kk)=Wall21NB(j)
Area(kk)=Area(Wall21NB(j))
k=k+1
face(1,Wall21NB(j))=k
face(1,kk)=k
facenode1(1,Wall21NB(j))=node(1,Wall21NB(j))
facenode2(1,Wall21NB(j))=node(2,Wall21NB(j))
kk=kk+1
enddo

kk=1505
do j=1,6
open(12,file='Wall23 NBs.txt')
read(12,*) Wall23NB(j)
nb(3,Wall23NB(j))=kk
nb(3,kk)=Wall23NB(j)
Area(kk)=Area(Wall23NB(j))
k=k+1
face(3,Wall23NB(j))=k
face(3,kk)=k
facenode1(3,Wall23NB(j))=node(3,Wall23NB(j))
facenode2(3,Wall23NB(j))=node(1,Wall23NB(j))
kk=kk+1
enddo

!By addition of image cells,totally we have 1510 cells.
return
END SUBROUTINE



end program AliGHAFFARIYAN
